### ISSUE TITLE
Publishing the latest Docker image

### ISSUE THREAD

**Issue by truckfondue** [RallySoftware/jenkins-build-light#14]
Thanks for accepting my changes to `url-patch` and this repo. 

Could you be so kind as to publish the docker image with those changes? I would like to consume the image from Docker Hub.

Thank you kindly!

**Comment by coldpour** [comment]
hey @truckfondue, I think I pushed it about 6 days ago. can you confirm that the new version is working for you?

**Comment by truckfondue** [comment]
thanks for your help a few years back! 🙌
